/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.testndk.app;

public class SWIGTYPE_p__int {
  private long swigCPtr;

  protected SWIGTYPE_p__int(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p__int() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p__int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

